all:
	nim c -r all.nim
	#nim c -r mjunit2xray.nim falconc_unit_tests_junit.xml
each:
	nim c -r t_welcome.nim
	nim c -r t_kmers.nim
	nim c -r t_gc.nim
	nim c -r t_overlapFilter.nim
	nim c -r t_pbcromwell.nim
	nim c -r t_pbreports.nim
	nim c -r t_stats.nim
	nim c -r t_rotate.nim

.PHONY: all
