Test Three: Only rotate first sequence - only sequence in whitelist

  $ echo 'first' > whitelist
  $ falconc circ-orient --window 20 -s 2 -i small.fasta -w whitelist -o small.out3.fasta > junk
  $ cat small.out3.fasta
  >first shifted_by_bp:-60/180
  CTTTTCAAGGCTCGTCTGTGCTTTAGATAATTATGAAAAGGAAACAGTTGGGGTGTGCTTGCTTATAGGAGTCTATATGA
  CCCATTGGGAAGACTCTTCTATAAAAACAGATGAAATTTTAGGAATCCTCTTTGTGGGCACTTAAAGCCCATGAAGCAAC
  ACAAGAAGCTATACAATTGT
  >second shifted_by_bp:-0/180
  AGGAATCCTCTTTGTGGGCACTTAAAGCCCATGAAGCAACACAAGAAGCTATACAATTGTCTTTTCAAGGCTCGTCTGTG
  CTTTAGATAATTATGAAAAGGAAACAGTTGGGGTGTGCTTGCTTATAGGAGTCTATATGACCCATTGGGAAGACTCTTCT
  ATAAAAACAGATGAAATTTT
  >third shifted_by_bp:-0/180
  AGGAATCCTCTTTGTGGGCACTTAAAGCCCATGAAGCAACACAAGAAGCTATACAATTGTCTTTTCAAGGCTCGTCTGTG
  CTTTAGATAATTATGAAAAGGAAACAGTTGGGGTGTGCTTGCTTATAGGAGTCTATATGACCCATTGGGAAGACTCTTCT
  ATAAAAACAGATGAAATTTT
  >fourth shifted_by_bp:-0/180
  AGGAATCCTCTTTGTGGGCACTTAAAGCCCATGAAGCAACACAAGAAGCTATACAATTGTCTTTTCAAGGCTCGTCTGTG
  CTTTAGATAATTATGAAAAGGAAACAGTTGGGGTGTGCTTGCTTATAGGAGTCTATATGACCCATTGGGAAGACTCTTCT
  ATAAAAACAGATGAAATTTT
